name: 定制化配置
description: 提交定制化配置疑问
title: 'custom:'
labels: [custom]
body:
  - type: markdown
    id: preface
    attributes:
      value: "你好！感谢你为 Dream 提交定制化配置建议。在开始之前，我们非常推荐阅读一遍[《开源最佳实践》](https://github.com/LinuxSuRen/open-source-best-practice)，这会在很大程度上提高我们彼此的效率。"
  - type: markdown
    id: environment
    attributes:
      value: "## 环境信息"
  - type: input
    id: dream-version
    validations:
      required: false
    attributes:
      label: "你当前使用的 Dream 版本"
      description: "可以在主题 `theme.yaml` 文件中找到。"
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: description
    attributes:
      label: "描述一下此定制化内容"
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: "补充信息"
      description: "如果你还有其他需要提供的信息或解决思路，可以在这里填写。"
